#pragma once
#include "Core/NumericTypes.h"

#define HYDRO_KEY_UNKNOWN            U16_MAX
#define HYDRO_KEY_SPACE              32
#define HYDRO_KEY_APOSTROPHE         39  
#define HYDRO_KEY_COMMA              44  
#define HYDRO_KEY_MINUS              45  
#define HYDRO_KEY_PERIOD             46  
#define HYDRO_KEY_SLASH              47  
#define HYDRO_KEY_0                  48
#define HYDRO_KEY_1                  49
#define HYDRO_KEY_2                  50
#define HYDRO_KEY_3                  51
#define HYDRO_KEY_4                  52
#define HYDRO_KEY_5                  53
#define HYDRO_KEY_6                  54
#define HYDRO_KEY_7                  55
#define HYDRO_KEY_8                  56
#define HYDRO_KEY_9                  57
#define HYDRO_KEY_SEMICOLON          59  
#define HYDRO_KEY_EQUAL              61  
#define HYDRO_KEY_A                  65
#define HYDRO_KEY_B                  66
#define HYDRO_KEY_C                  67
#define HYDRO_KEY_D                  68
#define HYDRO_KEY_E                  69
#define HYDRO_KEY_F                  70
#define HYDRO_KEY_G                  71
#define HYDRO_KEY_H                  72
#define HYDRO_KEY_I                  73
#define HYDRO_KEY_J                  74
#define HYDRO_KEY_K                  75
#define HYDRO_KEY_L                  76
#define HYDRO_KEY_M                  77
#define HYDRO_KEY_N                  78
#define HYDRO_KEY_O                  79
#define HYDRO_KEY_P                  80
#define HYDRO_KEY_Q                  81
#define HYDRO_KEY_R                  82
#define HYDRO_KEY_S                  83
#define HYDRO_KEY_T                  84
#define HYDRO_KEY_U                  85
#define HYDRO_KEY_V                  86
#define HYDRO_KEY_W                  87
#define HYDRO_KEY_X                  88
#define HYDRO_KEY_Y                  89
#define HYDRO_KEY_Z                  90
#define HYDRO_KEY_LEFT_BRACKET       91  
#define HYDRO_KEY_BACKSLASH          92  
#define HYDRO_KEY_RIGHT_BRACKET      93  
#define HYDRO_KEY_GRAVE_ACCENT       96  
#define HYDRO_KEY_WORLD_1            161 
#define HYDRO_KEY_WORLD_2            162 
#define HYDRO_KEY_ESCAPE             256
#define HYDRO_KEY_ENTER              257
#define HYDRO_KEY_TAB                258
#define HYDRO_KEY_BACKSPACE          259
#define HYDRO_KEY_INSERT             260
#define HYDRO_KEY_DELETE             261
#define HYDRO_KEY_RIGHT              262
#define HYDRO_KEY_LEFT               263
#define HYDRO_KEY_DOWN               264
#define HYDRO_KEY_UP                 265
#define HYDRO_KEY_PAGE_UP            266
#define HYDRO_KEY_PAGE_DOWN          267
#define HYDRO_KEY_HOME               268
#define HYDRO_KEY_END                269
#define HYDRO_KEY_CAPS_LOCK          280
#define HYDRO_KEY_SCROLL_LOCK        281
#define HYDRO_KEY_NUM_LOCK           282
#define HYDRO_KEY_PRINT_SCREEN       283
#define HYDRO_KEY_PAUSE              284
#define HYDRO_KEY_F1                 290
#define HYDRO_KEY_F2                 291
#define HYDRO_KEY_F3                 292
#define HYDRO_KEY_F4                 293
#define HYDRO_KEY_F5                 294
#define HYDRO_KEY_F6                 295
#define HYDRO_KEY_F7                 296
#define HYDRO_KEY_F8                 297
#define HYDRO_KEY_F9                 298
#define HYDRO_KEY_F10                299
#define HYDRO_KEY_F11                300
#define HYDRO_KEY_F12                301
#define HYDRO_KEY_F13                302
#define HYDRO_KEY_F14                303
#define HYDRO_KEY_F15                304
#define HYDRO_KEY_F16                305
#define HYDRO_KEY_F17                306
#define HYDRO_KEY_F18                307
#define HYDRO_KEY_F19                308
#define HYDRO_KEY_F20                309
#define HYDRO_KEY_F21                310
#define HYDRO_KEY_F22                311
#define HYDRO_KEY_F23                312
#define HYDRO_KEY_F24                313
#define HYDRO_KEY_F25                314
#define HYDRO_KEY_KP_0               320
#define HYDRO_KEY_KP_1               321
#define HYDRO_KEY_KP_2               322
#define HYDRO_KEY_KP_3               323
#define HYDRO_KEY_KP_4               324
#define HYDRO_KEY_KP_5               325
#define HYDRO_KEY_KP_6               326
#define HYDRO_KEY_KP_7               327
#define HYDRO_KEY_KP_8               328
#define HYDRO_KEY_KP_9               329
#define HYDRO_KEY_KP_DECIMAL         330
#define HYDRO_KEY_KP_DIVIDE          331
#define HYDRO_KEY_KP_MULTIPLY        332
#define HYDRO_KEY_KP_SUBTRACT        333
#define HYDRO_KEY_KP_ADD             334
#define HYDRO_KEY_KP_ENTER           335
#define HYDRO_KEY_KP_EQUAL           336
#define HYDRO_KEY_LEFT_SHIFT         340
#define HYDRO_KEY_LEFT_CONTROL       341
#define HYDRO_KEY_LEFT_ALT           342
#define HYDRO_KEY_LEFT_SUPER         343
#define HYDRO_KEY_RIGHT_SHIFT        344
#define HYDRO_KEY_RIGHT_CONTROL      345
#define HYDRO_KEY_RIGHT_ALT          346
#define HYDRO_KEY_RIGHT_SUPER        347
#define HYDRO_KEY_MENU               348
#define HYDRO_KEY_TOTAL              HYDRO_KEY_MENU

#if defined(_MSC_VER)
#pragma warning(push)
#pragma warning(disable: 4309)
#endif
namespace Hydro
{
    enum class KeyCode
    {
        Unknown = HYDRO_KEY_UNKNOWN,
        Space = HYDRO_KEY_SPACE,
        Apostrophe = HYDRO_KEY_APOSTROPHE,
        Comma = HYDRO_KEY_COMMA,
        Minus = HYDRO_KEY_MINUS,
        Period = HYDRO_KEY_PERIOD,
        Slash = HYDRO_KEY_SLASH,
        Key0 = HYDRO_KEY_0,
        Key1 = HYDRO_KEY_1,
        Key2 = HYDRO_KEY_2,
        Key3 = HYDRO_KEY_3,
        Key4 = HYDRO_KEY_4,
        Key5 = HYDRO_KEY_5,
        Key6 = HYDRO_KEY_6,
        Key7 = HYDRO_KEY_7,
        Key8 = HYDRO_KEY_8,
        Key9 = HYDRO_KEY_9,
        SemiColon = HYDRO_KEY_SEMICOLON,
        Equal = HYDRO_KEY_EQUAL,
        KeyA = HYDRO_KEY_A,
        KeyB = HYDRO_KEY_B,
        KeyC = HYDRO_KEY_C,
        KeyD = HYDRO_KEY_D,
        KeyE = HYDRO_KEY_E,
        KeyF = HYDRO_KEY_F,
        KeyG = HYDRO_KEY_G,
        KeyH = HYDRO_KEY_H,
        KeyI = HYDRO_KEY_I,
        KeyJ = HYDRO_KEY_J,
        KeyK = HYDRO_KEY_K,
        KeyL = HYDRO_KEY_L,
        KeyM = HYDRO_KEY_M,
        KeyN = HYDRO_KEY_N,
        KeyO = HYDRO_KEY_O,
        KeyP = HYDRO_KEY_P,
        KeyQ = HYDRO_KEY_Q,
        KeyR = HYDRO_KEY_R,
        KeyS = HYDRO_KEY_S,
        KeyT = HYDRO_KEY_T,
        KeyU = HYDRO_KEY_U,
        KeyV = HYDRO_KEY_V,
        KeyW = HYDRO_KEY_W,
        KeyX = HYDRO_KEY_X,
        KeyY = HYDRO_KEY_Y,
        KeyZ = HYDRO_KEY_Z,
        LeftBracket = HYDRO_KEY_LEFT_BRACKET,
        BackSlash = HYDRO_KEY_BACKSLASH,
        RightBracket = HYDRO_KEY_RIGHT_BRACKET,
        GraveAccent = HYDRO_KEY_GRAVE_ACCENT,
        World1 = HYDRO_KEY_WORLD_1,
        World2 = HYDRO_KEY_WORLD_2,
        Escape = HYDRO_KEY_ESCAPE,
        Enter = HYDRO_KEY_ENTER,
        Tab = HYDRO_KEY_TAB,
        Backspace = HYDRO_KEY_BACKSPACE,
        Insert = HYDRO_KEY_INSERT,
        Delete = HYDRO_KEY_DELETE,
        Right = HYDRO_KEY_RIGHT,
        Left = HYDRO_KEY_LEFT,
        Down = HYDRO_KEY_DOWN,
        Up = HYDRO_KEY_UP,
        PageUp = HYDRO_KEY_PAGE_UP,
        PageDown = HYDRO_KEY_PAGE_DOWN,
        Home = HYDRO_KEY_HOME,
        End = HYDRO_KEY_END,
        CapsLock = HYDRO_KEY_CAPS_LOCK,
        ScrollLock = HYDRO_KEY_SCROLL_LOCK,
        NumLock = HYDRO_KEY_NUM_LOCK,
        PrintScreen = HYDRO_KEY_PRINT_SCREEN,
        Pause = HYDRO_KEY_PAUSE,
        F1 = HYDRO_KEY_F1,
        F2 = HYDRO_KEY_F2,
        F3 = HYDRO_KEY_F3,
        F4 = HYDRO_KEY_F4,
        F5 = HYDRO_KEY_F5,
        F6 = HYDRO_KEY_F6,
        F7 = HYDRO_KEY_F7,
        F8 = HYDRO_KEY_F8,
        F9 = HYDRO_KEY_F9,
        F10 = HYDRO_KEY_F10,
        F11 = HYDRO_KEY_F11,
        F12 = HYDRO_KEY_F12,
        F13 = HYDRO_KEY_F13,
        F14 = HYDRO_KEY_F14,
        F15 = HYDRO_KEY_F15,
        F16 = HYDRO_KEY_F16,
        F17 = HYDRO_KEY_F17,
        F18 = HYDRO_KEY_F18,
        F19 = HYDRO_KEY_F19,
        F20 = HYDRO_KEY_F20,
        F21 = HYDRO_KEY_F21,
        F22 = HYDRO_KEY_F22,
        F23 = HYDRO_KEY_F23,
        F24 = HYDRO_KEY_F24,
        F25 = HYDRO_KEY_F25,
        Numpad0 = HYDRO_KEY_KP_0,
        Numpad1 = HYDRO_KEY_KP_1,
        Numpad2 = HYDRO_KEY_KP_2,
        Numpad3 = HYDRO_KEY_KP_3,
        Numpad4 = HYDRO_KEY_KP_4,
        Numpad5 = HYDRO_KEY_KP_5,
        Numpad6 = HYDRO_KEY_KP_6,
        Numpad7 = HYDRO_KEY_KP_7,
        Numpad8 = HYDRO_KEY_KP_8,
        Numpad9 = HYDRO_KEY_KP_9,
        NumpadDecimal = HYDRO_KEY_KP_DECIMAL,
        NumpadDivide = HYDRO_KEY_KP_DIVIDE,
        NumpadMultiply = HYDRO_KEY_KP_MULTIPLY,
        NumpadSubtract = HYDRO_KEY_KP_SUBTRACT,
        NumpadAdd = HYDRO_KEY_KP_ADD,
        NumpadEnter = HYDRO_KEY_KP_ENTER,
        NumpadEqual = HYDRO_KEY_KP_EQUAL,
        LeftShift = HYDRO_KEY_LEFT_SHIFT,
        LeftControl = HYDRO_KEY_LEFT_CONTROL,
        LeftAlt = HYDRO_KEY_LEFT_ALT,
        LeftSuper = HYDRO_KEY_LEFT_SUPER,
        RightShift = HYDRO_KEY_RIGHT_SHIFT,
        RightControl = HYDRO_KEY_RIGHT_CONTROL,
        RightAlt = HYDRO_KEY_RIGHT_ALT,
        RightSuper = HYDRO_KEY_RIGHT_SUPER,
        Menu = HYDRO_KEY_MENU,
        Total = Menu
    };
}

#if defined(_MSC_VER)
#pragma warning(pop)
#endif