function(add_nova_application NAME TYPE STD SOURCES)
    add_executable(${NAME} ${SOURCES})
    if(STD STREQUAL "CXX23")
        set(CXXSTD cxx_std_23)
    elseif (STD STREQUAL "CXX20")
        set(CXXSTD cxx_std_20)
    elseif (STD STREQUAL "CXX17")
        set(CXXSTD cxx_std_17)
    elseif (STD STREQUAL "CXX14")
        set(CXXSTD cxx_std_14)
    elseif (STD STREQUAL "CXX11")
        set(CXXSTD cxx_std_11)
    endif ()
    target_compile_features(${NAME} PRIVATE ${CXXSTD})
    target_link_libraries(${NAME} PUBLIC NovaEngine)
    target_compile_definitions(${NAME} PRIVATE NOVA_APPLICATION_DIR="${CMAKE_CURRENT_SOURCE_DIR}")
    target_include_directories(${NAME} PRIVATE Source)
    if(TYPE MATCHES "GRAPHICS|GAME")
        if(CMAKE_BUILD_TYPE MATCHES Release OR CMAKE_BUILD_TYPE MATCHES MinSizeRel)
            set_target_properties(${NAME} PROPERTIES WIN32_EXECUTABLE TRUE)
        endif ()
    endif ()
endfunction()